### PR TITLE
UserSettings improvements

### PR DESCRIPTION
**Pull request by henrikingo**

### CODE REVIEW

**Comment by mfleming** [comment]
@henrikingo can you break out these changes into separate PRs? Or at least rename this PR ?

**Comment by mfleming** [comment]
Why do we need to throttle function calls? Changing the magnitude and pvalue doesn't trigger change detection.

**Comment by henrikingo** [comment]
> Why do we need to throttle function calls? Changing the magnitude and pvalue doesn't trigger change detection.

When you drag the slider the onchange handler fires all the time. This is a workaround for saying "onWheneverUserIsActuallyDoneChangingTheValue". The goal is to send one POST not thousands.

**Comment by mfleming** [comment]
> When you drag the slider the onchange handler fires all the time. This is a workaround for saying "onWheneverUserIsActuallyDoneChangingTheValue". The goal is to send one POST not thousands.

Aha, got it. Thanks.

**Comment by henrikingo** [comment]
Approved?

**Review by mfleming — APPROVED** [review]

**Pull request merged**
