### PR TITLE
Add Playwright for frontend testing + our very own Nyrkiö integration

### PR DESCRIPTION
**Pull request by henrikingo**
Adds 1 simple test: Check that the logo is on the front page

### CODE REVIEW

**Comment by henrikingo** [comment]
Let me know what you think :-)

**Comment by mfleming** [comment]
> Let me know what you think :-)

I'm definitely in favour of having frontend tests :)

If this is working go ahead and merge.

**Comment by henrikingo** [comment]
So what did you want me to do again...? If I select squash and merge, it will not do a merge commit that points to this PR? You want "Create merge commit", right?

**Comment by mfleming** [comment]
Yep create merge commit

**Pull request merged**
